// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5AlL25-mWQYvZA5jAPkHYy2Ieig5IwWc',
    appId: '1:181139355134:android:6f1664527bdbf7b0cebcaf',
    messagingSenderId: '181139355134',
    projectId: 'practice-app-5b2cb',
    databaseURL: 'https://practice-app-5b2cb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'practice-app-5b2cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs96dg-vQhFXohkELdT9hcLRebOROUm2s',
    appId: '1:181139355134:ios:5ab88b3d8578ad07cebcaf',
    messagingSenderId: '181139355134',
    projectId: 'practice-app-5b2cb',
    databaseURL: 'https://practice-app-5b2cb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'practice-app-5b2cb.appspot.com',
    iosClientId: '181139355134-h915e0cmu1eq15hbaavqejvq7lbf4gh3.apps.googleusercontent.com',
    iosBundleId: 'com.example.second255',
  );
}
